apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: demo-pipeline-run-1
  namespace: tekton-demo
spec:
  serviceAccount: build-bot
  pipelineRef:
    name: demo-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: git-tektondemo
    - name: web-image
      resourceRef:
        name: image-tektondemo