apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tutorial-pipeline-run-1
  namespace: tekton-demo
spec:
  serviceAccount: build-bot
  pipelineRef:
    name: tutorial-pipeline
  resources:
    - name: source-repo
      resourceRef:
        name: git-tektondemo
    - name: web-image
      resourceRef:
        name: image-tektondemo